# Generated by Django 3.2.18 on 2023-05-01 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coordinate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Search_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Search_MoviePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movie_photos/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plainmap.search_movie')),
            ],
        ),
        migrations.CreateModel(
            name='Search_Movie_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plainmap.search_location')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plainmap.search_movie')),
            ],
        ),
    ]
