# Generated by Django 3.2.18 on 2023-05-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plainmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_movie_location',
            name='location',
        ),
        migrations.RemoveField(
            model_name='search_movie_location',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='search_moviephoto',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Search_Location',
        ),
        migrations.DeleteModel(
            name='Search_Movie',
        ),
        migrations.DeleteModel(
            name='Search_Movie_Location',
        ),
        migrations.DeleteModel(
            name='Search_MoviePhoto',
        ),
    ]
